### ISSUE TITLE
Package name typo?

### ISSUE THREAD

**Issue by favoyang** [VaLiuM09/VPG-Core#14]
Since 0.3.0 the package is renamed to `co.mindport.builder.core` (`com` without `m`). Does it a typo?

**Comment by VaLiuM09** [comment]
Hi,
it's not a typo, our domain (once it goes online) will be `minport.co` so it made sense to rename the package accordingly.
It does look a bit like one though...

**Comment by favoyang** [comment]
> it's not a typo

Okay, the package has been updated at OpenUPM: https://openupm.com/packages/co.mindport.builder.core/?subPage=pipelines
